name: 04 Testing secrets and variables

on:
  push

jobs:
  secrets_and_variables:
    runs-on: ubuntu-latest
    steps:
      - name: "Log secrets and variables"
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          NODE_ENV: ${{ vars.NODE_ENV }}
        run: |
          echo "Secret: $MONGO_URL, Variable: $NODE_ENV"
